package com.techpuram.app.gpsmapcamera

import android.content.Intent
import android.net.Uri
import android.os.Bundle
import android.os.Build
import android.util.Log
import android.view.WindowManager
import android.widget.Toast
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Edit
import androidx.compose.material.icons.filled.PinDrop
import androidx.compose.material.icons.filled.Upload
import androidx.compose.material.icons.filled.Verified
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.toArgb
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import coil.compose.rememberAsyncImagePainter
import com.google.android.gms.maps.model.CameraPosition
import com.google.android.gms.maps.model.LatLng
import com.google.maps.android.compose.*
import com.techpuram.app.gpsmapcamera.ui.theme.GPSmapCameraTheme
import kotlinx.coroutines.launch
import android.graphics.BitmapFactory
import java.security.MessageDigest

class PhotoPreviewActivity1 : ComponentActivity() {
    private val TAG = "PhotoPreviewActivity"

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        // Get data from intent
        val imageUri = intent.getStringExtra("imageUri")
        val latitude = intent.getStringExtra("latitude")
        val longitude = intent.getStringExtra("longitude")
        val address = intent.getStringExtra("address")

        // Set status bar color
        window?.let {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                it.addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS)
                it.statusBarColor = Color.Black.toArgb()
                val wic = androidx.core.view.WindowCompat.getInsetsController(it, it.decorView)
                wic.isAppearanceLightStatusBars = false
            }
        }

        setContent {
            GPSmapCameraTheme {
                PhotoPreviewScreen(
                    imageUri = imageUri,
                    latitude = latitude,
                    longitude = longitude,
                    address = address,
                    onSubmit = { editedUri ->
                        // Navigate to Gallery with the edited image
                        val intent = Intent(this, ResultActivity::class.java).apply {
                            putExtra("imageUri", editedUri.toString())
                        }
                        startActivity(intent)
                        finish()
                    },
                    onCancel = {
                        finish() // Go back to camera
                    }
                )
            }
        }
    }
}

@Composable
fun PhotoPreviewScreen(
    imageUri: String?,
    latitude: String?,
    longitude: String?,
    address: String?,
    onSubmit: (Uri) -> Unit,
    onCancel: () -> Unit
) {
    val context = LocalContext.current
    val TAG = "PhotoPreviewScreen"
    val scope = rememberCoroutineScope()

    var streetNumber by remember { mutableStateOf("") }
    var street by remember { mutableStateOf("") }
    var apartment by remember { mutableStateOf("") }
    var city by remember { mutableStateOf("") }
    var state by remember { mutableStateOf("") }
    var zipCode by remember { mutableStateOf("") }
    var country by remember { mutableStateOf("") }
    var customName by remember { mutableStateOf("") }

    // New state for proof generation
    var showProofDialog by remember { mutableStateOf(false) }
    var generatingProof by remember { mutableStateOf(false) }
    var proofId by remember { mutableStateOf("") }
    var proofChecksum by rememberSaveable { mutableStateOf("") }
    var isProofGenerated by remember { mutableStateOf(false) }

    val lat = latitude?.toDoubleOrNull()
    val lon = longitude?.toDoubleOrNull()

    fun parseAddress(fullAddress: String?) {
        Log.d(TAG, "Parsing address: $fullAddress")

        if (fullAddress.isNullOrBlank()) {
            Log.d(TAG, "Address is null or blank, skipping parsing")
            return
        }

        val parts = fullAddress.split(",").map { it.trim() }
        Log.d(TAG, "Address parts: $parts")

        try {
            // Reset editable fields
            streetNumber = ""
            street = ""
            apartment = ""
            city = ""
            state = ""
            zipCode = ""
            country = ""

            // Handle address parsing
            if (parts.isNotEmpty()) {
                // Street number: usually first number-like part
                val numberPattern = Regex("^\\d+[A-Za-z\\-\\d]*$")
                if (numberPattern.matches(parts[0])) {
                    streetNumber = parts[0]
                }

                // Combine street name: 2nd part
                if (parts.size > 1) {
                    street = parts[1]
                }

                // Add locality if available
                if (parts.size > 3) {
                    val locality = parts.subList(2, 4).joinToString(", ")
                    street += ", $locality"
                }

                // City
                if (parts.size > 4) {
                    city = parts[4]
                }

                // State and PIN
                if (parts.size > 5) {
                    val match = Regex("(.+?)\\s+(\\d{6})").find(parts[5])
                    if (match != null) {
                        state = match.groupValues[1].trim()
                        zipCode = match.groupValues[2]
                    } else {
                        state = parts[5]
                    }
                }

                // Country
                if (parts.size > 6) {
                    country = parts[6]
                }
            }

            Log.d(TAG, "Parsed: Street #: $streetNumber, Street: $street, City: $city, State: $state, ZIP: $zipCode, Country: $country")
        } catch (e: Exception) {
            Log.e(TAG, "Error parsing address: ${e.message}", e)
        }
    }

    // Function to generate proof
    fun generateProof(imageUri: Uri) {
        generatingProof = true

        scope.launch {
            try {
                // Read the image
                val inputStream = context.contentResolver.openInputStream(imageUri)
                val bitmap = BitmapFactory.decodeStream(inputStream)
                inputStream?.close()

                // Create a PDF for verification
                val verificationManager = VerificationManager(context, okhttp3.OkHttpClient())
                val pdfFile = verificationManager.createPdfFromImage(bitmap)

                // Generate checksum
                val md = MessageDigest.getInstance("SHA-256")
                val bytes = pdfFile?.readBytes() ?: ByteArray(0)
                val digest = md.digest(bytes)
                proofChecksum = digest.joinToString("") { "%02x".format(it) }

                // Generate a proof ID (would normally come from server)
                // For demo purposes, using first 15 chars of the checksum
                proofId = proofChecksum.take(15).uppercase()

                // Simulate upload to server
                kotlinx.coroutines.delay(1500) // Simulate network delay

                isProofGenerated = true
                generatingProof = false

                Toast.makeText(context, "Proof generated successfully!", Toast.LENGTH_SHORT).show()
            } catch (e: Exception) {
                Log.e(TAG, "Error generating proof: ${e.message}", e)
                Toast.makeText(context, "Failed to generate proof: ${e.message}", Toast.LENGTH_SHORT).show()
                generatingProof = false
            }
        }
    }

    LaunchedEffect(address) {
        parseAddress(address)
    }

    // Proof Generation Dialog
    if (showProofDialog) {
        AlertDialog(
            onDismissRequest = {
                if (!generatingProof) showProofDialog = false
            },
            title = { Text("Location Proof Generator") },
            text = {
                Column(
                    modifier = Modifier.padding(8.dp),
                    verticalArrangement = Arrangement.spacedBy(12.dp)
                ) {
                    if (generatingProof) {
                        Column(
                            horizontalAlignment = Alignment.CenterHorizontally,
                            modifier = Modifier.fillMaxWidth()
                        ) {
                            CircularProgressIndicator()
                            Spacer(modifier = Modifier.height(8.dp))
                            Text("Generating proof... Please wait")
                        }
                    } else if (isProofGenerated) {
                        Column {
                            Row(
                                verticalAlignment = Alignment.CenterVertically,
                                modifier = Modifier.fillMaxWidth()
                            ) {
                                Icon(
                                    Icons.Filled.Verified,
                                    contentDescription = "Verified",
                                    tint = MaterialTheme.colorScheme.primary,
                                    modifier = Modifier.size(24.dp)
                                )
                                Spacer(modifier = Modifier.width(8.dp))
                                Text(
                                    "Proof Generated Successfully!",
                                    style = MaterialTheme.typography.titleMedium,
                                    color = MaterialTheme.colorScheme.primary
                                )
                            }

                            Spacer(modifier = Modifier.height(16.dp))

                            Text("Verification ID:", fontWeight = FontWeight.Bold)
                            Text(
                                proofId,
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .padding(8.dp)
                                    .background(MaterialTheme.colorScheme.primaryContainer, RoundedCornerShape(4.dp))
                                    .padding(8.dp),
                                textAlign = TextAlign.Center
                            )

                            Spacer(modifier = Modifier.height(8.dp))

                            Text("Document Checksum:", fontWeight = FontWeight.Bold)
                            Text(
                                proofChecksum.take(32) + "...",
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .padding(horizontal = 8.dp)
                                    .background(MaterialTheme.colorScheme.secondaryContainer, RoundedCornerShape(4.dp))
                                    .padding(8.dp),
                                fontSize = 12.sp,
                                textAlign = TextAlign.Center
                            )

                            Spacer(modifier = Modifier.height(16.dp))

                            Text(
                                "The proof has been generated and is ready to upload. You can use the verification ID to confirm the authenticity of this location data.",
                                style = MaterialTheme.typography.bodySmall
                            )
                        }
                    } else {
                        Text(
                            "Generate a cryptographic proof that this photo was taken at this location. " +
                                    "This creates a verifiable record that can be validated by third parties."
                        )

                        OutlinedTextField(
                            value = proofId,
                            onValueChange = { proofId = it },
                            label = { Text("Verification ID (Optional)") },
                            modifier = Modifier.fillMaxWidth(),
                            placeholder = { Text("Leave blank to generate automatically") }
                        )
                    }
                }
            },
            confirmButton = {
                if (generatingProof) {
                    // Show nothing while generating
                } else if (isProofGenerated) {
                    Button(onClick = {
                        // Here you would upload to server
                        Toast.makeText(context, "Proof uploaded to server!", Toast.LENGTH_SHORT).show()
                        showProofDialog = false
                    }) {
                        Text("Upload Proof")
                        Spacer(modifier = Modifier.width(4.dp))
                        Icon(Icons.Default.Upload, contentDescription = "Upload")
                    }
                } else {
                    Button(onClick = {
                        imageUri?.let { uri ->
                            generateProof(Uri.parse(uri))
                        }
                    }) {
                        Text("Generate Proof")
                    }
                }
            },
            dismissButton = {
                if (!generatingProof) {
                    TextButton(onClick = { showProofDialog = false }) {
                        Text("Close")
                    }
                }
            }
        )
    }

    LazyColumn(
        modifier = Modifier
            .fillMaxSize()
            .padding(16.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {
        item {
            Card(
                modifier = Modifier.fillMaxWidth(),
                shape = RoundedCornerShape(16.dp),
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant),
                elevation = CardDefaults.cardElevation(defaultElevation = 4.dp)
            ) {
                Column(modifier = Modifier.padding(16.dp)) {
                    imageUri?.let {
                        Image(
                            painter = rememberAsyncImagePainter(Uri.parse(it)),
                            contentDescription = "Captured Image",
                            modifier = Modifier
                                .fillMaxWidth()
                                .height(240.dp)
                                .clip(RoundedCornerShape(8.dp)),
                            contentScale = ContentScale.Crop
                        )
                        Spacer(modifier = Modifier.height(16.dp))
                    } ?: Text("No Image Available", style = MaterialTheme.typography.bodyLarge)

                    Row(
                        verticalAlignment = Alignment.CenterVertically,
                        horizontalArrangement = Arrangement.spacedBy(8.dp)
                    ) {
                        Icon(Icons.Filled.PinDrop, contentDescription = "Location Pin", tint = MaterialTheme.colorScheme.primary)
                        Text(
                            text = "Location Details",
                            style = MaterialTheme.typography.titleMedium
                        )
                    }
                    Divider(modifier = Modifier.padding(vertical = 8.dp))

                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        verticalAlignment = Alignment.CenterVertically,
                        horizontalArrangement = Arrangement.SpaceBetween
                    ) {
                        Column(modifier = Modifier.weight(1f)) { // Allow address to take more space
                            Text(text = "Address:", style = MaterialTheme.typography.bodyMedium, color = MaterialTheme.colorScheme.secondary)
                            Text(text = address ?: "Unknown", style = MaterialTheme.typography.bodyLarge)
                        }
                        Spacer(modifier = Modifier.width(8.dp))
                        if (lat != null && lon != null) {
                            Box(
                                modifier = Modifier
                                    .size(80.dp)
                                    .clip(RoundedCornerShape(8.dp))
                            ) {
                                GoogleMap(
                                    modifier = Modifier.fillMaxSize(),
                                    cameraPositionState = rememberCameraPositionState {
                                        position = CameraPosition.fromLatLngZoom(LatLng(lat, lon), 13f)
                                    },
                                    uiSettings = MapUiSettings(zoomControlsEnabled = false, scrollGesturesEnabled = false, rotationGesturesEnabled = false, tiltGesturesEnabled = false, compassEnabled = false, myLocationButtonEnabled = false)
                                ) {
                                    Marker(
                                        state = MarkerState(position = LatLng(lat, lon)),
                                        title = "Photo Location"
                                    )
                                }
                            }
                        }
                    }
                }
            }
        }

        item {
            Card(
                modifier = Modifier.fillMaxWidth(),
                shape = RoundedCornerShape(16.dp),
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant),
                elevation = CardDefaults.cardElevation(defaultElevation = 4.dp)
            ) {
                Column(modifier = Modifier.padding(16.dp)) {
                    Row(
                        verticalAlignment = Alignment.CenterVertically,
                        horizontalArrangement = Arrangement.spacedBy(8.dp)
                    ) {
                        Icon(Icons.Filled.Edit, contentDescription = "Edit Details", tint = MaterialTheme.colorScheme.primary)
                        Text(text = "Edit Details", style = MaterialTheme.typography.titleMedium)
                    }
                    Divider(modifier = Modifier.padding(vertical = 8.dp))

                    OutlinedTextField(
                        value = customName,
                        onValueChange = { customName = it },
                        label = { Text("Custom Name (Optional)") },
                        modifier = Modifier.fillMaxWidth().padding(bottom = 8.dp),
                        shape = RoundedCornerShape(8.dp),
                        leadingIcon = { Icon(Icons.Filled.Edit, contentDescription = "Custom Name") }
                    )

                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.spacedBy(8.dp)
                    ) {
                        OutlinedTextField(
                            value = streetNumber,
                            onValueChange = { streetNumber = it },
                            label = { Text("Street Number") },
                            modifier = Modifier.weight(0.4f).padding(bottom = 8.dp),
                            shape = RoundedCornerShape(8.dp)
                        )
                        OutlinedTextField(
                            value = street,
                            onValueChange = { street = it },
                            label = { Text("Street Name") },
                            modifier = Modifier.weight(0.6f).padding(bottom = 8.dp),
                            shape = RoundedCornerShape(8.dp)
                        )
                    }

                    OutlinedTextField(
                        value = apartment,
                        onValueChange = { apartment = it },
                        label = { Text("Apartment/Unit (Optional)") },
                        modifier = Modifier.fillMaxWidth().padding(bottom = 8.dp),
                        shape = RoundedCornerShape(8.dp)
                    )
                    OutlinedTextField(
                        value = city,
                        onValueChange = { city = it },
                        label = { Text("City") },
                        modifier = Modifier.fillMaxWidth().padding(bottom = 8.dp),
                        shape = RoundedCornerShape(8.dp)
                    )

                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.spacedBy(8.dp)
                    ) {
                        OutlinedTextField(
                            value = state,
                            onValueChange = { state = it },
                            label = { Text("State") },
                            modifier = Modifier.weight(0.5f).padding(bottom = 8.dp),
                            shape = RoundedCornerShape(8.dp)
                        )
                        OutlinedTextField(
                            value = zipCode,
                            onValueChange = { zipCode = it },
                            label = { Text("ZIP Code") },
                            modifier = Modifier.weight(0.5f).padding(bottom = 8.dp),
                            shape = RoundedCornerShape(8.dp)
                        )
                    }

                    OutlinedTextField(
                        value = country,
                        onValueChange = { country = it },
                        label = { Text("Country") },
                        modifier = Modifier.fillMaxWidth().padding(bottom = 8.dp),
                        shape = RoundedCornerShape(8.dp)
                    )
                }
            }
        }

        // Add new proof verification card
        item {
            Card(
                modifier = Modifier.fillMaxWidth(),
                shape = RoundedCornerShape(16.dp),
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.tertiaryContainer),
                elevation = CardDefaults.cardElevation(defaultElevation = 4.dp)
            ) {
                Column(
                    modifier = Modifier.padding(16.dp),
                    horizontalAlignment = Alignment.CenterHorizontally
                ) {
                    Row(
                        verticalAlignment = Alignment.CenterVertically,
                        horizontalArrangement = Arrangement.spacedBy(8.dp)
                    ) {
                        Icon(
                            Icons.Filled.Verified,
                            contentDescription = "Verify",
                            tint = MaterialTheme.colorScheme.onTertiaryContainer
                        )
                        Text(
                            text = "Location Verification",
                            style = MaterialTheme.typography.titleMedium,
                            color = MaterialTheme.colorScheme.onTertiaryContainer
                        )
                    }

                    Spacer(modifier = Modifier.height(8.dp))
                    Divider(modifier = Modifier.padding(vertical = 4.dp))
                    Spacer(modifier = Modifier.height(4.dp))

                    Text(
                        text = if (isProofGenerated)
                            "A cryptographic proof has been generated for this location."
                        else
                            "Generate a cryptographic proof that this photo was taken at this location.",
                        style = MaterialTheme.typography.bodyMedium,
                        textAlign = TextAlign.Center,
                        modifier = Modifier.padding(horizontal = 8.dp)
                    )

                    Spacer(modifier = Modifier.height(12.dp))

                    if (isProofGenerated) {
                        Row(
                            modifier = Modifier
                                .fillMaxWidth()
                                .padding(horizontal = 8.dp)
                                .background(Color.White.copy(alpha = 0.2f), RoundedCornerShape(8.dp))
                                .padding(8.dp),
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Column(modifier = Modifier.weight(1f)) {
                                Text(
                                    "Verification ID:",
                                    style = MaterialTheme.typography.labelMedium,
                                    color = MaterialTheme.colorScheme.onTertiaryContainer
                                )
                                Text(
                                    proofId,
                                    style = MaterialTheme.typography.titleMedium,
                                    color = MaterialTheme.colorScheme.onTertiaryContainer
                                )
                            }
                            Button(
                                onClick = { showProofDialog = true },
                                colors = ButtonDefaults.buttonColors(
                                    containerColor = MaterialTheme.colorScheme.tertiary
                                )
                            ) {
                                Text("Details")
                            }
                        }
                    } else {
                        Button(
                            onClick = { showProofDialog = true },
                            colors = ButtonDefaults.buttonColors(
                                containerColor = MaterialTheme.colorScheme.tertiary
                            ),
                            modifier = Modifier.fillMaxWidth(0.8f)
                        ) {
                            Icon(
                                Icons.Filled.Verified,
                                contentDescription = "Generate Proof",
                                modifier = Modifier.size(20.dp)
                            )
                            Spacer(modifier = Modifier.width(8.dp))
                            Text("Generate Location Proof")
                        }
                    }
                }
            }
        }

        item {
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                Button(
                    onClick = { onCancel() },
                    modifier = Modifier.weight(1f),
                    shape = RoundedCornerShape(16.dp),
                    colors = ButtonDefaults.buttonColors(
                        containerColor = MaterialTheme.colorScheme.secondaryContainer,
                        contentColor = MaterialTheme.colorScheme.onSecondaryContainer
                    )
                ) {
                    Text("Cancel")
                }

                Button(
                    onClick = {
                        // Build address with all components
                        val streetPart = buildString {
                            append(streetNumber.takeIf { it.isNotBlank() } ?: "")
                            if (street.isNotBlank()) {
                                if (this.isNotEmpty()) append(" ")
                                append(street)
                            }
                            if (apartment.isNotBlank()) {
                                if (this.isNotEmpty()) append(", ")
                                append("Apt $apartment")
                            }
                        }

                        val updatedAddress = buildString {
                            if (streetPart.isNotBlank()) append(streetPart)

                            if (city.isNotBlank()) {
                                if (this.isNotEmpty()) append(", ")
                                append(city)
                            }

                            if (state.isNotBlank() || zipCode.isNotBlank()) {
                                if (this.isNotEmpty()) append(", ")
                                if (state.isNotBlank()) append(state)
                                if (zipCode.isNotBlank()) {
                                    if (state.isNotBlank()) append(" ")
                                    append(zipCode)
                                }
                            }

                            if (country.isNotBlank()) {
                                if (this.isNotEmpty()) append(", ")
                                append(country)
                            }
                        }

                        val finalAddress = if (updatedAddress.isBlank()) address ?: "Unknown Address" else updatedAddress
                        Log.d(TAG, "Final address for image: $finalAddress")

                        imageUri?.let {
                            val lat = latitude?.toDoubleOrNull()
                            val lon = longitude?.toDoubleOrNull()

                            if (lat != null && lon != null) {
                                val editedUri = addMapAndTextToImage(context, Uri.parse(it), finalAddress, lat, lon)
                                editedUri?.let { newUri ->
                                    onSubmit(newUri)
                                    Toast.makeText(context, "Image saved with location data!", Toast.LENGTH_SHORT).show()
                                } ?: Toast.makeText(context, "Failed to save image.", Toast.LENGTH_SHORT).show()
                            } else {
                                Toast.makeText(context, "Location data is missing or invalid.", Toast.LENGTH_SHORT).show()
                            }
                        }
                    },
                    modifier = Modifier.weight(1f),
                    shape = RoundedCornerShape(16.dp),
                    contentPadding = PaddingValues(16.dp)
                ) {
                    Text("Save & Continue", style = MaterialTheme.typography.titleMedium)
                }
            }
        }
    }
}